### ISSUE TITLE
启动训练脚本出现偶发性ray.exceptions.ActorDiedError错误

### ISSUE THREAD

**Issue by metaqiang** [volcengine/verl#10]
您好，我们对您的项目非常感兴趣，有个问题想请教一下。

我们在执行训练脚本`examples/ppo_trainer/run_deepseek7b_llm.sh`的时候，有时会遇到ray.exceptions.ActorDiedError错误，这个问题应该如何解决？以下是错误栈：

```
(main_task pid=90508) Using LocalLogger is deprecated. The constructor API will change 
Error executing job with overrides: ['data.train_files=/hyzhou/gsm8k/train.parquet', 'data.val_files=/hyzhou/gsm8k/test.parquet', 'data.train_batch_size=1024', 'data.val_batch_size=1312', 'data.max_prompt_length=512', 'data.max_response_length=512', 'actor_rollout_ref.model.path=/hyzhou/deepseek-ai/deepseek-llm-7b-instruct', 'actor_rollout_ref.actor.optim.lr=1e-6', 'actor_rollout_ref.actor.ppo_mini_batch_size=256', 'actor_rollout_ref.actor.ppo_micro_batch_size=32', 'actor_rollout_ref.actor.fsdp_config.param_offload=False', 'actor_rollout_ref.actor.fsdp_config.grad_offload=False', 'actor_rollout_ref.actor.fsdp_config.optimizer_offload=False', 'actor_rollout_ref.rollout.log_prob_micro_batch_size=128', 'actor_rollout_ref.rollout.tensor_model_parallel_size=4', 'actor_rollout_ref.rollout.name=vllm', 'actor_rollout_ref.rollout.gpu_memory_utilization=0.4', 'actor_rollout_ref.ref.log_prob_micro_batch_size=128', 'actor_rollout_ref.ref.fsdp_config.param_offload=True', 'critic.optim.lr=1e-5', 'critic.model.path=/hyzhou/deepseek-ai/deepseek-llm-7b-instruct', 'critic.model.enable_gradient_checkpointing=False', 'critic.ppo_micro_batch_size=32', 'critic.model.fsdp_config.param_offload=False', 'critic.model.fsdp_config.grad_offload=False', 'critic.model.fsdp_config.optimizer_offload=False', 'algorithm.kl_ctrl.kl_coef=0.001', 'trainer.critic_warmup=0', 'trainer.logger=[console]', 'trainer.project_name=verl_example_gsm8k', 'trainer.experiment_name=deepseek_llm_7b_function_rm', 'trainer.n_gpus_per_node=8', 'trainer.nnodes=1', 'trainer.save_freq=-1', 'trainer.total_epochs=15']
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/verl/trainer/main_ppo.py", line 97, in main
    ray.get(main_task.remote(config))
  File "/usr/local/lib/python3.10/dist-packages/ray/_private/auto_init_hook.py", line 21, in auto_init_wrapper
    return fn(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python3.10/dist-packages/ray/_private/worker.py", line 2745, in get
    values, debugger_breakpoint = worker.get_objects(object_refs, timeout=timeout)
  File "/usr/local/lib/python3.10/dist-packages/ray/_private/worker.py", line 901, in get_objects
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(ActorDiedError): ray::main_task() (pid=90508, ip=10.90.67.83)
  File "/usr/local/lib/python3.10/dist-packages/verl/trainer/main_ppo.py", line 182, in main_task
    trainer.fit()
  File "/usr/local/lib/python3.10/dist-packages/verl/trainer/ppo/ray_trainer.py", line 433, in fit
    gen_batch_output = self.actor_rollout_wg.generate_sequences(gen_batch)
  File "/usr/local/lib/python3.10/dist-packages/single_controller/ray/base.py", line 42, in func
    output = ray.get(output)
ray.exceptions.ActorDiedError: The actor died unexpectedly before finishing this task.
	class_name: create_colocated_worker_cls.<locals>.WorkerDict
	actor_id: 9ca8e95bb0140a3b4f8c56f001000000
	pid: 91584
	name: 0pTaDIWorkerDict_0:0
	namespace: 1d4891db-ba8e-4ee5-8ec8-5d6e1b3b466e
	ip: 10.90.67.83
The actor is dead because all references to the actor were removed.
```

很期待您的回复~

**Comment by PeterSH6** [comment]
你好@metaqiang，请问安装的ray版本是什么？是2.10吗？

**Comment by metaqiang** [comment]
谢谢，我们的问题已经解决，是因为ray版本安装错误，换成2.10即可

**Comment by Austin-QW** [comment]
Hi, I solved the same question. Just modify the parameter num_cpus=0.1 to num_cpus=1 in
verl/trainer/config/ppo_trainer.yaml

resources_per_worker: # resources for each env worker
num_cpus: 1 (the original is 0.1)
