### ISSUE TITLE
[ray] latest ray compatibility

### ISSUE THREAD

**Issue by eric-haibin-lin** [volcengine/verl#46]
commit: 50ac7252f97cf39997344237bca74162b2dc6d79
environment: with image `verlai/verl:vemlp-th2.4.0-cu124-vllm0.6.3-ray2.10-te1.7-v0.0.3`

command:
```bash
# prepare checkpoints
python3 -c "import transformers; transformers.pipeline('text-generation', model='Qwen/Qwen2.5-0.5B-Instruct')"
# prepare dataset
python3 examples/data_preprocess/gsm8k.py --local_dir ~/data/gsm8k
# run training 
bash examples/ppo/run_gemma.sh "trainer.n_gpus_per_node=1 actor_rollout_ref.rollout.tensor_model_parallel_size=1 trainer.logger=['console'] critic.model.path=Qwen/Qwen2.5-0.5B-Instruct actor_rollout_ref.model.path=Qwen/Qwen2.5-0.5B-Instruct data.train_batch_size=256 actor_rollout_ref.actor.ppo_mini_batch_size=64 actor_rollout_ref.actor.ppo_micro_batch_size=2 critic.ppo_micro_batch_size=2" 


```

with the default ray version in the image (2.10), it works fine. But when upgraded to ray 2.40, it fails with:
```
[36m(WorkerDict pid=238403)[0m After building sharding manager, memory allocated (GB): 39.55978584289551, memory reserved (GB): 40.583984375
Error executing job with overrides: ['data.train_files=/root/data/gsm8k/train.parquet', 'data.val_files=/root/data/gsm8k/test.parquet', 'data.train_batch_size=512', 'data.val_batch_size=1312', 'data.max_prompt_length=1024', 'data.max_response_length=512', 'actor_rollout_ref.model.path=google/gemma-2-2b-it', 'actor_rollout_ref.actor.optim.lr=1e-6', 'actor_rollout_ref.actor.ppo_mini_batch_size=128', 'actor_rollout_ref.actor.ppo_micro_batch_size=4', 'actor_rollout_ref.actor.fsdp_config.param_offload=False', 'actor_rollout_ref.actor.fsdp_config.grad_offload=False', 'actor_rollout_ref.actor.fsdp_config.optimizer_offload=False', 'actor_rollout_ref.rollout.log_prob_micro_batch_size=4', 'actor_rollout_ref.rollout.tensor_model_parallel_size=2', 'actor_rollout_ref.rollout.name=vllm', 'actor_rollout_ref.rollout.gpu_memory_utilization=0.4', 'actor_rollout_ref.ref.log_prob_micro_batch_size=4', 'actor_rollout_ref.ref.fsdp_config.param_offload=True', 'critic.optim.lr=1e-5', 'critic.model.path=google/gemma-2-2b-it', 'critic.model.enable_gradient_checkpointing=False', 'critic.ppo_micro_batch_size=4', 'critic.model.fsdp_config.param_offload=False', 'critic.model.fsdp_config.grad_offload=False', 'critic.model.fsdp_config.optimizer_offload=False', 'algorithm.kl_ctrl.kl_coef=0.001', 'trainer.critic_warmup=0', 'trainer.logger=[console,tracking]', 'trainer.project_name=verl_example', 'trainer.experiment_name=gemma2b_function_rm', 'trainer.n_gpus_per_node=2', 'trainer.nnodes=1', 'trainer.save_freq=-1', 'trainer.test_freq=10', 'trainer.total_epochs=15', 'trainer.n_gpus_per_node=1', 'actor_rollout_ref.rollout.tensor_model_parallel_size=1', "trainer.logger=['console']", 'critic.model.path=Qwen/Qwen2.5-0.5B-Instruct', 'actor_rollout_ref.model.path=Qwen/Qwen2.5-0.5B-Instruct', 'data.train_batch_size=256', 'actor_rollout_ref.actor.ppo_mini_batch_size=64', 'actor_rollout_ref.actor.ppo_micro_batch_size=2', 'critic.ppo_micro_batch_size=2']
Traceback (most recent call last):
  File "/root/code/verl/verl/trainer/main_ppo.py", line 97, in main
    ray.get(main_task.remote(config))
  File "/root/miniconda3/lib/python3.10/site-packages/ray/_private/auto_init_hook.py", line 21, in auto_init_wrapper
    return fn(*args, **kwargs)
  File "/root/miniconda3/lib/python3.10/site-packages/ray/_private/client_mode_hook.py", line 103, in wrapper
    return func(*args, **kwargs)
  File "/root/miniconda3/lib/python3.10/site-packages/ray/_private/worker.py", line 2755, in get
    values, debugger_breakpoint = worker.get_objects(object_refs, timeout=timeout)
  File "/root/miniconda3/lib/python3.10/site-packages/ray/_private/worker.py", line 906, in get_objects
    raise value.as_instanceof_cause()
ray.exceptions.RayTaskError(ActorDiedError): [36mray::main_task()[39m (pid=237905, ip=172.24.0.16)
  File "/root/code/verl/verl/trainer/main_ppo.py", line 184, in main_task
    trainer.fit()
  File "/root/code/verl/verl/trainer/ppo/ray_trainer.py", line 418, in fit
    val_metrics = self._validate()
  File "/root/code/verl/verl/trainer/ppo/ray_trainer.py", line 303, in _validate
    test_output_gen_batch = self.actor_rollout_wg.generate_sequences(test_gen_batch)
  File "/root/code/verl/single_controller/ray/base.py", line 42, in func
    output = ray.get(output)
ray.exceptions.ActorDiedError: The actor died unexpectedly before finishing this task.
	class_name: create_colocated_worker_cls.<locals>.WorkerDict
	actor_id: 3b0ef1cf080649c136c7b1fd01000000
	pid: 238403
	name: clPTyRWorkerDict_0:0
	namespace: 26f7d252-15e2-4c1a-bd1a-cf4c3bf91adb
	ip: 172.24.0.16
The actor is dead because all references to the actor were removed.

```
Full log available: 
[ray_2_40.log](https://github.com/user-attachments/files/18134942/ray_2_40.log)

**Comment by PeterSH6** [comment]
Fixed by https://github.com/volcengine/verl/pull/65.

We should then integrate multiple WorkerGroups with one ResourcePool in the Megatron-LM backend in the following week.
And then support different placements by simply specifying them in the config file.
